# Tuned
MountainCarContinuous-v0:
  n_timesteps: !!float 50000
  policy: 'MlpPolicy'
  learning_rate: !!float 3e-4
  buffer_size: 50000
  batch_size: 512
  ent_coef: 0.1
  train_freq: 32
  gradient_steps: 32
  gamma: 0.9999
  tau: 0.01
  learning_starts: 0
  use_sde: True
  policy_kwargs: "dict(log_std_init=-3.67, net_arch=[64, 64])"

MsPacmanNoFrameskip-v4:
  env_wrapper:
    - stable_baselines3.common.atari_wrappers.AtariWrapper
  frame_stack: 4
  n_timesteps: !!float 100000
  policy: 'CnnPolicy'
  batch_size: 64
  #buffer_size: 1000000
  buffer_size: 100000
  gamma: 0.99
  learning_starts: 20000
  learning_rate: 0.0003
  tau: 1.0
  train_freq: 4
  target_update_interval: 8000
